### ISSUE TITLE
Miner in headless mode looking for config.json

### ISSUE THREAD

**Issue by bekman1** [toncoinpool/stratum-miner#5]
Hi devs
I wanna try your miner  in headless mode, all needed params was initialized in command line, but why miner looking for config.json file?
Can you please create a Linux miner package where all needed files in only one folder and not contain any subfolders with files?
I want integrate your miner in Awesome Miner system, but due small bug in Awesome Miner with copy of custom software to the destination rig (not correct create a file structure on destination system) I am unable to use your software.

Regards

**Comment by sadcatjam** [comment]
Hi, since version 2.0.0 client no longer crashes if `config.json` is not present

As for the flat directory structure, I can't promise, that it will be done anytime soon, if at all. You can try to build a linux headless version yourself with the desired directory structure and proper modifications to `baseBinaryPath` and `dataDir` in `src/electron/client/config.ts`
